# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  pathtosolution: 'PizzaBoxWeb'
  pathtoproject: 'PizzaBoxWeb/PizzaBoxWeb'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'PizzaSonar'
    organization: 'michaelbeneamatobruno-github'
    scannerMode: 'MSBuild'
    projectKey: '1e2927324795bd28be51a6905ae7b763e959cedf'
  displayName: 'SonarCloudPrepare'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(pathtosolution)

# BASIC TEST
- script: dotnet test
   --configuration $(buildConfiguration)
   --logger trx
   --no-build
   --results-directory $(Build.ArtifactStagingDirectory)/test/
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput='$(Build.ArtifactStagingDirectory)/coverage/'
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet Test'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(Build.ArtifactStagingDirectory)/test'
  displayName: 'Publish test results '

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(pathtoproject)/*.csproj'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(98319a34-14d7-4635-9df2-7e1c62e066ef)'
    appType: 'webApp'
    appName: PizzaBoxWebApplication
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
